function ee=ee(x)
global mu alpha beta B

N=sum(x);
lambda=beta*(x(3)+x(4)+x(5))/N;
lambdadash=betadash*(x(3)+x(4)+x(5))/N;

w =    [b*N,...
        mu*x(1),...
        mu*x(2),...
        mu*x(3),...
        mu*x(4),...
        (alpha+mu)*x(5),...
        lambda*x(1),...
        lambdadash*x(2),...
        (1-q)*gamma*x(3),...
        (1-qdash)*gammadash*x(4),...
        n*q*
        
               
 
        %in this vector w you will need to include the correct rates at
        %which the different events can happen in your model
P = sum(w); %total rate at which all events occur
ee=[cumsum(w/P),P]; %vector containing cumulative sum of the individual rates, followed by the total rate 